apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgA3hE+0EC3fTPRz+NFeVul9qrrbRe90vkfABZfWvfErLUYf4/c9Ad6CSF09N2Zvch9Q4dZG9fuJwm26rgnD7UZWqsYAID7gD1SzmZbNiHqe61OrZU1PDoqsIMhSXUx4iN+UvpJNPEuVjdKU5HQ3orVfwmDgoqjkpqxgi+Ba9ElwR2n31SKwgaCWYVn0nCD2w0ztRYGU6cxqKGnS5YrCPm+P8zwVDmxGZWhwBVGQ8j/ohzXAPOzAbDN0HGUDzhP9kbWDp+ve4CEl75Voo8MiqjO+5Q4gEFjZFU1sfwuUUbYFZ/u4Xijzv7xNon0py0QxhYXxBP3obgG9lhC7iv3qr9AmVkkRsXabOvpWJjGYF5FrvQnxz6cg/q6JqDBBUEeD+DRvVOHVO7xB6qNy3mWbwhKU7+v+B4RwLUBHHv+MK0L8GsLtmUjdE5sx72fiNoN9rS2tlw8C5J9auO9nPs+jcSjW+Mr1WoV8efFVAQ5UYxLkiqjEOCLvDyJmCfIJMeOCAB2gWaTTNrvUXPsw4YlswtNa5kUkxF1y0qxWbxbRzUEv6k5fAV5mYzrZmmlX+HFrWCZGlqJUXqaEfx6voKZvr04Qatp2pr0w02Qnss7pZs4GGs0Xwn4iENjnutRM6sxdu+T79eNz/zMrCOPaegz+cQBmkkc+MFIng5DKCQzZqFzBgV68XFfXH8Xi9Xhsrqh13yWTyhDVpyRfVybWLZEb3yHQV1LD8H2GOJF49P9U39j6fNYkghC41Fy1KOjbkFfehtxYxyOg4/ppgrbsqJ+DWoApsbXCzMof2D3KOqN28KWEHtJt01rl5JgLU3vGNb83X9I6B4GCtQZLQeOgsF4pg89Dsallp9/mYRFc9Zyrm+SM0fIwjXspIDX43yLZDrdMF47HISb9pw6/JduodRwGojA4BoPW1IQfI5PF9BualY8Cb7PDVSMBrfRo4rlkDzEMgxNx86st5R7VzKo877Ub0ifzTAK+qRnHDaYcfItJbn2eIjkr+7OSEev06MyquJ99ASFQumipYukteERhBX0z8xwEisvlggLbORDArrp4E6q4rlfBvkOzTgf7KwgYcIYE907qE9PmAas2Jz0g71zZXfUX0EILxYTZapI+bsG+MLbqC+1p4LF26wRygDUC+sKA/BgumvJNtMcW4vNw6pa8nRsI6D0Ie9v8QnWe0i7IMrjfpAQLmYV2Hme85kcYCsirBENQezi6EQl2JK0AR3IhD7cHmHj8cz57S8YqrKyjmRM7Qsko99FFCD0lmF6V/kCGCi0vQQqZDEr1DpMbQLaqhUtQgwdSOeGBQzRavdj0Qi3wdV6CkzDbbdURqZ03aP72UEMsHviB1kfS+dQxM2dRCZzqMFkQEOpMvXJwLz20fBmR68r6qaeU
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

